name: Benchmark
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
  pull-requests: write
jobs:
  benchmark:
    name: Run Benchmarks
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: macOS-26
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install Swiftly And Swift
        run: |
          curl -L https://download.swift.org/swiftly/darwin/swiftly.pkg > swiftly.pkg
          installer -pkg swiftly.pkg -target CurrentUserHomeDirectory

          ~/.swiftly/bin/swiftly init

          . "$HOME/.swiftly/env.sh"
          hash -r

          swiftly install --use --assume-yes
          swiftly link --assume-yes

          echo "$HOME/.swiftly/bin" >> $GITHUB_PATH
      - name: Swift Version
        run: which swift && swift --version
      - name: Install jemalloc
        run: |
          echo "/opt/homebrew/bin:/usr/local/bin" >> $GITHUB_PATH
          brew install jemalloc
      - name: Run Parsing Benchmarks
        run: |
          export ENABLE_BENCHMARK=1
          swift package benchmark --no-progress --format markdown >> $GITHUB_STEP_SUMMARY
