name: CI
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "Package.swift"
      - "Sources/**"
      - "Tests/**"
      - "TestPlans/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - "Package.swift"
      - "Sources/**"
      - "Tests/**"
      - "TestPlans/**"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}.app/Contents/Developer"
    strategy:
      matrix:
        include:
          - xcode: "Xcode_26.0"
            runsOn: macOS-26
            name: "macOS 26, SPM 6.2.0 Test"
    steps:
      - uses: actions/checkout@v4
      - name: Swift Version
        run: xcrun swift --version
      - name: Install SwiftLint
        run: brew install swiftlint --quiet
      - name: Install swift-format
        run: |
          brew install swiftformat --quiet
      - name: Install xcbeautify
        run: |
          brew install xcbeautify --quiet
      - name: SwiftLint
        run: swiftlint --strict --config .swiftlint.yml .
      - name: Swift Format Check
        run: |
          swiftformat --lint-only --config .swiftformat.conf . --strict
      - name: Run Tests
        run: |
          set -o pipefail && \
          xcodebuild test \
          -scheme BinaryParseKit-Package \
          -destination 'platform=macOS' \
          -skipMacroValidation | xcbeautify --renderer github-actions

          # https://github.com/swiftlang/swift-package-manager/issues/9163
          # set -o pipefail && xcrun swift test -c debug --enable-code-coverage --xunit-output $TEST_RESULTS_DIR/xunit.xml 2>&1 | xcbeautify --renderer github-actions
